#include "gpio.h"

void gpio_reset(void) {
	GPIO_PUD_OFF(PIN(3));
	GPIO_PUD_OFF(PIN(5));
	GPIO_PUD_OFF(PIN(7));
	GPIO_PUD_OFF(PIN(10));
	GPIO_PUD_OFF(PIN(11));
	GPIO_PUD_OFF(PIN(12));
	GPIO_PUD_OFF(PIN(13));
	GPIO_PUD_OFF(PIN(15));
	GPIO_PUD_OFF(PIN(16));
	GPIO_PUD_OFF(PIN(18));
	GPIO_PUD_OFF(PIN(19));
	GPIO_PUD_OFF(PIN(21));
	GPIO_PUD_OFF(PIN(22));
	GPIO_PUD_OFF(PIN(23));
	GPIO_PUD_OFF(PIN(24));
	GPIO_PUD_OFF(PIN(26));

	GPIO_INPUT(PIN(3));
	GPIO_INPUT(PIN(5));
	GPIO_INPUT(PIN(7));
	GPIO_INPUT(PIN(10));
	GPIO_INPUT(PIN(11));
	GPIO_INPUT(PIN(12));
	GPIO_INPUT(PIN(13));
	GPIO_INPUT(PIN(15));
	GPIO_INPUT(PIN(16));
	GPIO_INPUT(PIN(18));
	GPIO_INPUT(PIN(19));
	GPIO_INPUT(PIN(21));
	GPIO_INPUT(PIN(22));
	GPIO_INPUT(PIN(23));
	GPIO_INPUT(PIN(24));
	GPIO_INPUT(PIN(26));
}
